CREATE TABLE word_entry (
                            id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            language VARCHAR(2)   NOT NULL,
                            lemma    VARCHAR(100) NOT NULL,
                            CONSTRAINT uq_word_entry_language_lemma UNIQUE (language, lemma)
);

CREATE TABLE translation (
                             id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             word_entry_id   BIGINT       NOT NULL REFERENCES word_entry (id),
                             target_language VARCHAR(2)   NOT NULL,
                             translation     VARCHAR(100) NOT NULL,
                             CONSTRAINT uq_translation_word_entry_target_translation UNIQUE (word_entry_id, target_language, translation)
);