CREATE TABLE app_user (
                          id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email      VARCHAR(255)             NOT NULL,
                          role       VARCHAR(10)              NOT NULL DEFAULT 'USER',
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT uq_app_user_email UNIQUE (email)
);

CREATE TABLE user_identity (
                               id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id          BIGINT       NOT NULL REFERENCES app_user (id),
                               provider         VARCHAR(20)  NOT NULL,
                               provider_user_id VARCHAR(100) NOT NULL,
                               CONSTRAINT uq_user_identity_provider_provider_user_id UNIQUE (provider, provider_user_id)
);