CREATE TABLE user_vocabulary (
                                 id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id         BIGINT      NOT NULL REFERENCES app_user (id),
                                 word_entry_id   BIGINT      NOT NULL REFERENCES word_entry (id),
                                 target_language VARCHAR(2)  NOT NULL,
                                 status          VARCHAR(10) NOT NULL,
                                 CONSTRAINT uq_user_vocabulary_user_word_entry_target UNIQUE (user_id, word_entry_id, target_language)
);