spring.application.name=backend
spring.config.import=optional:classpath:application-local.properties

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Application
frontend.url=https://lexic-on.onrender.com
github.api.url=https://api.github.com

# Server
# Limit Tomcat's worker threads to reduce memory usage on constrained hosts
server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2

# Azure Translator
azure.translator.endpoint=https://api.cognitive.microsofttranslator.com
azure.translator.key=${AZURE_TRANSLATOR_KEY}
azure.translator.region=${AZURE_TRANSLATOR_REGION}
